[package]
name = "packed-seq"
version = "0.1.0"
edition = "2021"

[dependencies]
wide = "0.7.32"
rand = "0.9.0"
mem_dbg = "0.2.4"
cfg-if = "1.0.0"

# Optional (de)serialization using epserde.
epserde = { version = "0.6.1", optional = true }

# Optional pyclass atrributes for some objects.
pyo3 = { version = "0.23.4", features = ["extension-module"], optional = true }
